### ISSUE TITLE
Make Tinypilot ready for bullseye

### ISSUE THREAD

**Issue by mcmufffin** [tiny-pilot/ansible-role-tinypilot#143]
Hi,

i just tested tinypilot on bullseye and ran into a few problems:

python-pip requirement by ansible must be replaced by python3-pip
libjpeg8-dev is replaced by libjpeg9-dev for ustreamer
dnspython version to old (just used dnspython without version which worked fine)

besides that tinypilot itself works like charm under bullseye.

Would be happy to see native compatibility.

Thanks!
regards

**Comment by mtlynch** [comment]
Thanks for letting me know!

How are you testing bullseye? I haven't seen any Raspberry Pi OS Lite builds for bullseye yet.

**Comment by mcmufffin** [comment]
Hi,

yeah thats true, bullseye is not avaliable as an image but you can allready upgrade by replacing the sources list and doing a normal debian upgrade.

I know, its unstable, but it will surely be released soon and most of the things should also apply when it becomes stable (e.g. python2 removing)

Regards

**Comment by nicolas-schreiber** [comment]
Awesome, just FYI, I got it working following @mcmufffin s information.
I changed `libjpeg8-dev` and `libjpeg8` to 9 in `ansible-role-ustreamer/blob/master/tasks/main.yml` but I had to remove `libjpeg-turbo8` as well.
Then I changed `python-pip` to `python3-pip` in `ansible-role-tinypilot/tasks/main.yml`
I did not have to change `dnspython` though

**Comment by mtlynch** [comment]
The official Raspbian bullseye image is now available:

https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-11-08/2021-10-30-raspios-bullseye-armhf-lite.zip

**Comment by mtlynch** [comment]
The uStreamer portion should be working as of https://github.com/tiny-pilot/ansible-role-ustreamer/pull/48
