### ISSUE TITLE
Refactoring: share common logic between privileged scripts

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/ansible-role-tinypilot#147]
We have some duplication in the [privileged scripts](https://github.com/tiny-pilot/ansible-role-tinypilot/tree/master/files), especially in [pro](https://github.com/tiny-pilot/ansible-role-tinypilot-pro/tree/master/files). For example, the path to the USB gadget / configfs is spelled out in multiple files, or the procedure for (re-)initializing the gadget. It would be clearer, if there was just one source of truth for those values, and defining functions for common procedures could make the scripts more expressive.

An idea would be to pull out a script file with common constants and procedures (e.g. `lib.sh`) that can be `source`’d in the other scripts. Example:

```bash
#!/bin/bash

readonly USB_GADGET_PATH="/sys/kernel/config/usb_gadget/g1"

initialize_gadget() {
  ls /sys/class/udc > "${USB_GADGET_PATH}/UDC"
  chmod 777 /dev/hidg0
  chmod 777 /dev/hidg1
}
```

Then, in [`eject-mass-storage`](https://github.com/tiny-pilot/ansible-role-tinypilot-pro/blob/9525e9a01e46388aa9d41e7beab627a5a4f6fbaf/files/eject-mass-storage#L41):

```bash
source lib.sh # or whatever the file name is

# ...

if "${is_force_mode}"; then
  echo '' > "${USB_GADGET_PATH}/UDC"
  trap initialize_gadget EXIT
fi
```

**Comment by mtlynch** [comment]
Oh, that's a good idea.

**Comment by jotaen4tinypilot** [comment]
In https://github.com/tiny-pilot/ansible-role-tinypilot-image-builder/pull/7 we placed the shared code inside a `lib/` folder to keep the scripts folder tidy and “discoverable”, so we should probably follow the same convention elsewhere.

Also remember:

> Libraries must have a `.sh` extension and should not be executable.
> (https://google.github.io/styleguide/shellguide.html#file-extensions)

**Comment by jotaen4tinypilot** [comment]
Plus, when `source`ing, we should make sure that it works regardless of the current working directory. E.g.:

```bash
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
```

**Comment by mtlynch** [comment]
@rw4nn - The remaining work here for 2011-10 is to backport the refactoring changes from ansible-role-tinypilot-pro to ansible-role-tinypilot

**Comment by rw4nn** [comment]
Yes, on it :muscle:
