### ISSUE TITLE
Apple doesn't recognize TinyPilot keyboard in pre-boot

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/ansible-role-tinypilot#151]
Apple devices don't implement the HID spec correctly, so it fails to recognize the TinyPilot keyboard in pre-boot. The upstream Linux kernel [has a workaround](https://forum.tinypilotkvm.com/-132/keyboard-and-mouse-not-working-with-macbook-pro-usb-c), but it hasn't made its way into Raspbian yet.

A reader on my blog [shared instructions](https://mtlynch.io/key-mime-pi/#comment-35) for compiling custom builds of the kernel modules and confirmed that they work on his Pi Zero + Apple devices:

### Instructions

```bash
git clone https://github.com/raspberrypi/linux/
git checkout 4e5d621498df # ("overlays: Reduce Pi 4 vc4 CMA size to 320MB")
get the patch from https://0bin.net/paste/m6fB-sxx#ZF8Jp5ArPkDJS-W3ax5BROkPtkKi+hUH9F/mhgSL+Z1
git apply 0001-usb-gadget-f_hid-optional-SETUP-SET_REPORT-mode.patch # apply patch

CONFIG_LOCALVERSION="-v7l-MY_CUSTOM_KERNEL" # set some environment variable
KERNEL=kernel

make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcmrpi_defconfig # default config pi zero
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- modules_prepare # prepare build environment for modules
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- M=drivers/usb/gadget/function/
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- M=drivers/usb/gadget/legacy/

mkdir -p apple-keyboard-fix
cp ./drivers/usb/gadget/legacy/g_hid.ko apple-keyboard-fix/ # grab the two modules
cp ./drivers/usb/gadget/function/usb_f_hid.ko apple-keyboard-fix/
```

>On the actual device/pi zero:

```bash
sudo cp /home/pi/apple-keyboard-fix/g_hid.ko /lib/modules/5.10.52+/kernel/drivers/usb/gadget/legacy/g_hid.ko
sudo cp /home/pi/apple-keyboard-fix/usb_f_hid.ko /lib/modules/5.10.52+/kernel/drivers/usb/gadget/function/usb_f_hid.ko
```

>I've been using the instructions from https://www.isticktoit.net/?p=1383 where you ned to add the following to the script /usr/bin/isticktoit_usb, after subclass configuration:

```bash
echo 1 > functions/hid.usb0/no_out_endpoint
```

>I've uploaded both compiled files to my google drive, if you want to skip the instructions above:
g_hid.ko (for kernel 5.10.52+): https://drive.google.com/file/d/17yx2yxFjIjcXplfqRHKXlQAKavysMoeA/view?usp=sharing
usb_f_hid.ko (for kernel 5.10.52+): https://drive.google.com/file/d/10xkzEgTdCPS0M4D1TMv80tlvLI5sY2Mz/view?usp=sharing

### Our fix

We should compile our own build for the Pi 4 and host it on a public TinyPilot URL.

This Ansible role should include logic that if the system is a Raspberry Pi with a kernel version without the workaround, we should download our custom kernel module builds and replace the built-in modules on the device.

I'm not sure if we need to replace both modules or only one.

**Comment by jotaen4tinypilot** [comment]
I’m probably not the best person to work on the Ansible side, but in case no one else has a Mac, I’d be happy to do testing on my end.
