### ISSUE TITLE
Automatically merge from Ansible Community -> Pro

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/ansible-role-tinypilot#163]
We should add an automatic action that performs the same function as the Github action we created for the tinypilot -> tinypilot-pro repo:

tiny-pilot/tinypilot#838

**Comment by rw4nn** [comment]
@mtlynch I think you need to set up the workflows permission for ansible-role repos and/or give my user the workflows permission, because currently I cannot push the new github workflow, getting this error:

```
> git push -u origin auto-merge-pro
To https://github.com/tiny-pilot/ansible-role-tinypilot.git
 ! [remote rejected] auto-merge-pro -> auto-merge-pro (refusing to allow an OAuth App to create or update workflow `.github/workflows/merge-pro.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/tiny-pilot/ansible-role-tinypilot.git'
```

Thanks a lot!

**Comment by mtlynch** [comment]
That's weird. You seem to have the same permissions here as you did on the tinypilot repo. If you keep getting rejected, can you just rename the `.github` folder to something else and I'll do a simple commit to fix the name?
