### ISSUE TITLE
Video fails after upgrading - libjpeg.so.8: cannot open shared object file

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/ansible-role-tinypilot#174]
Several users are [reporting](https://forum.tinypilotkvm.com/-212/tinypilot-no-longer-capturing-video) that uStreamer fails after they perform an upgrade:

```bash
/opt/ustreamer/ustreamer: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
```

This prevents uStreamer from launching and therefore hides the remote screen.

### Workaround

Reinstall the microSD from a [pre-made image](https://tinypilotkvm.com/faq/factory-reset).

### Other observations

* All affected users are using HDMI to USB dongles (their logs show `--encoder hw --format jpeg`)
* This seems to happen after an update
* This isn't introduced in 2.3.2 as some users reported it in 2.3.1
* It might be related to this change: https://github.com/tiny-pilot/ansible-role-ustreamer/pull/48

### Example user logs

* https://logs.tinypilotkvm.com/5umcSogn
* https://logs.tinypilotkvm.com/GSBFYqnh
* https://logs.tinypilotkvm.com/wAg5TV20

**Comment by jdeanwallace** [comment]
I've managed to recreate this issue by doing the following:
1. Install TinyPilot Pro `2.3.0`. This installs `libjpeg8`.
1. Update TinyPilot Pro to the latest version (`2.3.2`). This installs `libjpeg9`. After the update we'll have both `libjpeg8` and `libjpeg9` on the device.
1. Run `sudo apt-get autoremove`. This uninstalls `libjpeg8`, however the device's ustreamer build still relies on `libjpeg8`.
1. Restart the ustreamer service. This causes the following error on start up:
    ```
    error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
    ```

I'm not too sure how the `autoremove` step could have been executed, but I assume it depends on each user's setup. Nevertheless, it's our responsibility to ensure that our services are using the correct dependency versions.

Quick fix: Rebuild ustreamer
```bash
cd /opt/ustreamer/
sudo make clean
sudo make
sudo systemctl restart ustreamer.service
```

Possible long-term fix: Rebuild ustreamer when its [dependency packages are updated](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/dd4983a307f7d78cdb74374d2e86dec998627fd2/tasks/main.yml#L79-L82).

**Comment by jdeanwallace** [comment]
> And the time to do a build from source is only a few seconds on a Pi, IIRC.

These are the results rebuilding ustreamer on my RPi4B:
```
time bash -c 'make clean && make'
...
real	0m18.536s
user	0m16.171s
sys	0m2.341s
```

> it would get even more complicated if we try to figure out if any system libraries have changed since the last build

We can limit the scope of the fix to only rebuild ustreamer in the context of the current ansible run. So for example, we [register a variable to see if a package was installed](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/dd4983a307f7d78cdb74374d2e86dec998627fd2/tasks/main.yml#L110) then [add another conditional to build ustreamer](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/dd4983a307f7d78cdb74374d2e86dec998627fd2/tasks/main.yml#L125).

However, as you said, things get complicated if ansible fails to complete or the user hacks around on the device.

Should I go ahead with unconditionally building uStreamer from source every time?

**Comment by jdeanwallace** [comment]
Oh nevermind, I just realized that my "fix" wouldn't fix the issue retrospectively. We have to rebuild ustreamer.

**Comment by mtlynch** [comment]
Yeah, let's just build and take the hit. We can look into speedups in the future, but for now it's better to just get it working consistently.
