### ISSUE TITLE
Update Overhaul: Execute `get-tinypilot.sh` when performing a system update

### ISSUE THREAD

**Issue by jotaen4tinypilot** [tiny-pilot/ansible-role-tinypilot#204]
The [control flow for executing a system update currently goes like this](https://github.com/tiny-pilot/tinypilot-pro/blob/experimental/update-overhaul/UPDATE-WORKFLOW.md#update-via-the-web-ui):

1. TinyPilot app triggers Updater systemd service
2. Updater systemd service executes [`scripts/update-service`](https://github.com/tiny-pilot/tinypilot-pro/blob/master/scripts/update-service)
3. `update-service` script calls [`update` privileged script](https://github.com/tiny-pilot/ansible-role-tinypilot-pro/blob/master/files/update)
4. `update` privileged script downloads and executes `quick-install` script
5. `update-service` writes result into JSON file, to communicate back to the TinyPilot app.

[The new flow that is described in the `UPDATE-WORKFLOW` document](https://github.com/tiny-pilot/tinypilot-pro/blob/experimental/update-overhaul/UPDATE-WORKFLOW.md#update-via-the-web-ui-1) doesn’t apply to Community: the situation in Community is simpler, since we always download the latest version, so we don’t have to save and pass down the desired version. Effectively, we need to change step 4:

1.-3. (just as before, see above)
4. **(new) `update` privileged script downloads `get-tinypilot.sh` script and executes it**
5. (just as before, see above)

Note: since the `quick-install` script needs to stay where it is for backwards-compatibility, we could also consider to always go through it, instead of changing the `update` privileged script. In this case, this issue would be obsolete. Pro: just one single way how it’s being done. Con: an unnecessary indirection just for legacy reasons. Note, the latter (the Con) will become more apparent in Pro, since we need to pass down additional parameters.

> **⚠️⚠️⚠️
> Please hold off on merging until the second 2.4.2 milestone is complete.
> (See [the note of the second milestone](https://github.com/tiny-pilot/tinypilot-pro/issues/445).)
> ⚠️⚠️⚠️**

**Comment by mtlynch** [comment]
This is actually an ansible-role-tinypilot change. It doesn't have to happen in lockstep with the other M2 changes because the legacy `quick-install` will still work and delegate to get-tinypilot.sh.

**Comment by jdeanwallace** [comment]
Fixed in https://github.com/tiny-pilot/ansible-role-tinypilot/pull/211
