### ISSUE TITLE
Update Overhaul: Remove the use of the TinyPilot git repo in favor of the TinyPilot Debian package.

### ISSUE THREAD

**Issue by jdeanwallace** [tiny-pilot/ansible-role-tinypilot#218]
After having merged both https://github.com/tiny-pilot/tinypilot/pull/1046 and https://github.com/tiny-pilot/ansible-role-tinypilot/pull/214, we can remove the use of git for TinyPilot code. For example:
- [ ] https://github.com/tiny-pilot/ansible-role-tinypilot/blob/19100f2991a9afef8d9a42bdef6a4298545f3c6b/tasks/main.yml#L124-L135
- [x] https://github.com/tiny-pilot/ansible-role-tinypilot/blob/19100f2991a9afef8d9a42bdef6a4298545f3c6b/files/collect-debug-logs#L68-L70

**Comment by jdeanwallace** [comment]
Once we remove the TinyPilot repo and only rely on the TinyPilot Debian package, the [`build` step fails](https://app.circleci.com/pipelines/github/tiny-pilot/ansible-role-tinypilot/503/workflows/a098c9c1-87b0-48bd-b0e8-ab91c885d0c2/jobs/1118) because the TinyPilot Debian package is not part of this repo and only gets built in the [`tinypilot` repo](https://github.com/tiny-pilot/tinypilot/blob/1faf38d4bf30f58168bde1d9e6327e6e6ca60ed8/.circleci/config.yml#L62).

We could consider:
1. Merging the `ansible-role-tinypilot` repo with the `tinypilot` repo (as suggested before)
    * This seems to be where we are going in the long run.
1. Rebuild the TinyPilot Debian package as part of `ansible-role-tinypilot`'s CI.
    * This should be easy copy paste work.
1. Upload the TinyPilot Debian package somewhere so that we can reference it in the ansible playbook.
    * The file should have to be accessible via a static URL to avoid manually updating the reference.

**Comment by mtlynch** [comment]
I think we should:

1. Fix `collect-debug-logs` now
2. Mark the git install of ansible-role-tinypilot as deprecated
3. Punt the removal of the git logic until later

We'll probably end up folding ansible-role-tinypilot into the tinypilot repo, but it's too much churn right now to add another big change.

**Comment by jdeanwallace** [comment]
@jotaen4tinypilot – We can't remove the `tinypilot_repo_branch` variable from `ansible-role-tinypilot` yet because molecule still builds TinyPilot using the git repo. We first need a way to pass the TinyPilot Debian package to this repo's CircleCI `build` step. We'll most likely wait until we fold `ansible-role-tinypilot` into the `tinypilot` repo.
